services:
  pangea-kong-plugin:
    container_name: pangea-kong-container
    image: pangea_kong_plugin
    volumes:
      - ./config/pangea_kong_config.json:/etc/pangea_kong_config.json
    networks:
      - kong-net
    ports:
      - "8010:8000"
      - "8011:8001"
      - "8012:8002"
    environment:
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      PANGEA_AI_GUARD_TOKEN_SECRET: /run/secrets/pangea_ai_guard_token_secret
      PANGEA_KONG_CONFIG_FILE: /etc/pangea_kong_config.json

      # Disable DB so it need to set KONG_DECLARATIVE_CONFIG_STRING
      KONG_DATABASE: "off"

      # For OpenAI testing
      KONG_DECLARATIVE_CONFIG_STRING: '{"_format_version":"1.1", "services":[{"name":"test_service_openai","host":"api.openai.com","port":443,"protocol":"https", "routes":[{"name":"openairoutes","paths":["/chatgpt/user", "/chatgpt/dev"]}]}],"plugins":[{"name":"pangea_kong"}]}'
      # For local testing with a service running on host.docker.internal
      # KONG_DECLARATIVE_CONFIG_STRING: '{"_format_version":"1.1", "services":[{"name":"test_service_local","host":"host.docker.internal","port":8080,"protocol":"http", "routes":[{"name":"openairoutes","paths":["/chatgpt/user", "/chatgpt/dev"]}]}],"plugins":[{"name":"pangea_kong"}]}'

      # KONG_LOG_LEVEL: info
    secrets:
      - pangea_ai_guard_token_secret

networks:
  kong-net:
    external: true

secrets:
  pangea_ai_guard_token_secret:
    file: ./secrets/pangea_ai_guard_token.txt
