services:
  pangea-kong-plugin:
    container_name: kong-plugin-container
    image: kong_plugin
    networks:
      - kong-net
    ports:
      - "8010:8000"
      - "8011:8001"
      - "8012:8002"
    environment:
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      PANGEA_AI_GUARD_TOKEN: /run/secrets/pangea_ai_guard_token
    secrets:
      - pangea_ai_guard_token

networks:
  kong-net:
    external: true

secrets:
  pangea_ai_guard_token:
    file: ./secrets/pangea_ai_guard_token.txt
