_format_version: "3.0"
_transform: true

services:
- name: service_openai
  host: api.openai.com
  port: 443
  protocol: https
  routes:
    - name: openairoutes
      paths:
          - /chatgpt/user
          - /chatgpt/dev

- name: service_cohere
  host: api.cohere.ai
  port: 443
  protocol: https
  routes:
    - name: cohereroutes
      paths:
        - /cohere/user
        - /cohere/dev

plugins:
  - name: pangea-ai-guard
