_format_version: "3.0"
_transform: true

services:
- name: test_service_openai
  host: api.openai.com
  port: 443
  protocol: https
  routes:
    - name: openairoutes
      paths:
          - /chatgpt/user
          - /chatgpt/dev

- name: test_service_claude
  host: claude.ai
  port: 443
  protocol: https
  routes:
    - name: clauderoutes
      paths:
        - /claude/user
        - /claude/dev


- name: test_service_cohere
  host: api.cohere.ai
  port: 443
  protocol: https
  routes:
    - name: cohereroutes
      paths:
        - /cohere/user
        - /cohere/dev

- name: test_service_bedrock
  url: https://bedrock-runtime.us-west-2.amazonaws.com
  routes:
    - name: bedrockroutes
      paths:
        - /bedrock/user
        - /bedrock/dev

plugins:
  - name: pangea-ai-guard
